default:
  image: docker:27.0.2


build-data-ingestion:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/data-ingestion:latest --platform linux/amd64,linux/arm64 --file ./sense_core/data_ingestion.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/data-ingestion
  only:
    - main

build-simple-event-detection:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/simple-event-detection:latest --platform linux/amd64,linux/arm64 --file ./sense_core/simple_event_detection.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/simple-event-detection
  only:
    - main

build-knowledgebase:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/knowledgebase:latest --platform linux/amd64,linux/arm64 --file ./sense_core/knowledgebase.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/knowledgebase
  only:
    - main

build-semantic-event-log-bridge:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/semantic-event-log-bridge:latest --platform linux/amd64,linux/arm64 --file ./sense_core/semantic_event_log_bridge.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/semantic-event-log-bridge
  only:
    - main

build-event-to-state-causality:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/event-to-state-causality:latest --platform linux/amd64,linux/arm64 --file ./sense_core/event-to-state-causality/Dockerfile ./sense_core/event-to-state-causality
    - docker push $CI_REGISTRY/sense/sense-core/event-to-state-causality
  only:
    - main
