default:
  image: docker:20.10.16


build-data-ingestion:
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/data-ingestion:latest ./sense_core/data_ingestion.Containerfile
    - docker push $CI_REGISTRY/sense/sense-core/data-ingestion

build-simple-event-detection:
  stage: build
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/simple-event-detection:latest ./sense_core/simple_event_detection.Containerfile
    - docker push $CI_REGISTRY/sense/sense-core/simple-event-detection