default:
  image: docker:27.0.2


build-data-ingestion:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/data-ingestion:ontology-v2 --platform linux/amd64,linux/arm64 --file ./sense_core/data_ingestion.Containerfile ./sense_core --push
  only:
    - main

build-simple-event-detection:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/simple-event-detection:ontology-v2 --platform linux/amd64,linux/arm64 --file ./sense_core/simple_event_detection.Containerfile ./sense_core --push
  only:
    - main

build-knowledgebase:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/knowledgebase-amd64:ontology-v2 --platform linux/amd64 --file ./sense_core/knowledgebase.amd64.Containerfile ./sense_core --push
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/knowledgebase-arm64:ontology-v2 --platform linux/arm64 --file ./sense_core/knowledgebase.arm64.Containerfile ./sense_core --push
    - docker buildx imagetools create -t $CI_REGISTRY/sense/sense-core/knowledgebase:ontology-v2 $CI_REGISTRY/sense/sense-core/knowledgebase-amd64:ontology-v2 $CI_REGISTRY/sense/sense-core/knowledgebase-arm64:ontology-v2
  only:
    - main

build-semantic-event-log-bridge:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/semantic-event-log-bridge:ontology-v2 --platform linux/amd64,linux/arm64 --file ./sense_core/semantic_event_log_bridge.Containerfile ./sense_core --push
  only:
    - main

build-event-to-state-causality:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/event-to-state-causality:ontology-v2 --platform linux/amd64,linux/arm64 --file ./sense_core/event-to-state-causality/Dockerfile ./sense_core/event-to-state-causality --push
  only:
    - main
    
build-explanation-engine:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:27.0.2-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build -t $CI_REGISTRY/sense/sense-core/explanation-engine:ontology-v2 --platform linux/amd64,linux/arm64 --file ./sense_core/explanation-engine/Dockerfile ./sense_core/explanation-engine --push
  only:
    - main
