default:
  image: docker:20.10.16


build-data-ingestion:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/data-ingestion:latest --file data_ingestion.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/data-ingestion
  only:
    - main

build-simple-event-detection:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/simple-event-detection:latest --file simple_event_detection.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/simple-event-detection
  only:
    - main