default:
  image: docker:20.10.16


build-data-ingestion:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/data-ingestion:latest --file ./sense_core/data_ingestion.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/data-ingestion
  only:
    - main

build-simple-event-detection:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/simple-event-detection:latest --file ./sense_core/simple_event_detection.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/simple-event-detection
  only:
    - main

build-knowledgebase:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/knowledgebase:latest --file ./sense_core/knowledgebase.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/knowledgebase
  only:
    - main

build-semantic-event-log-bridge:
  stage: build
  tags:
    - linux-docker-runner
  services:
    - docker:20.10.16-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/sense/sense-core/semantic-event-log-bridge:latest --file ./sense_core/semantic_event_log_bridge.Containerfile ./sense_core
    - docker push $CI_REGISTRY/sense/sense-core/semantic-event-log-bridge
  only:
    - main
